### ISSUE TITLE
How to convert path object to svg?

### ISSUE THREAD

**Issue by rvk86** [flupke/pypotrace#12]
Probably a noob question, but I'm wonding how I get from a traced bitmap (so the result of the `.trace()` method on the `Bitmap` object) to svg (xml) format? I can't find anything in the documentation about this.

Thanks in advance for the answer!

**Comment by flupke** [comment]
I don't know SVG but you can probably find lots of information on it online.

**Comment by flupke** [comment]
The idea behind pypotrace was to expose just enough of potrace's API to get vector data from a bitmap. What is done with the vectorized output is outside of the scope of pypotrace. Why not use the `potrace` binary directly to create your SVG?

**Comment by rvk86** [comment]
Yeah, okay, makes sense. I've been successfully using potrace directly already, but doing that requires me to write to disk several times. I figured doing it all in memory would be more efficient. Thanks anyway. I'm going to dig into it!
