### ISSUE TITLE
undefined symbol: _ZdlPvm

### ISSUE THREAD

**Issue by ClinuxMDL** [flupke/pypotrace#13]
>>> import potrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/potrace/__init__.py", line 1, in <module>
    from potrace._potrace import *
  File "potrace/_potrace.pyx", line 1, in init potrace._potrace (potrace/_potrace.c:10067)
ImportError: /root/anaconda2/lib/python2.7/site-packages/potrace/bezier.so: undefined symbol: _ZdlPvm

Could you help me please?
Thank you very much.

YJ

**Comment by lrouch-gpsw** [comment]
Hi, how was the package compiled?

**Comment by flupke** [comment]
Hi, how was the package compiled?

**Comment by ClinuxMDL** [comment]
I have tried the two: 1) Build from source, just shown in readme. 2) pip install pypotrace.The above could be installed successfully. But import potrace would fail. Bezier.so was directly used during my installation, would I  need to recompile it ?
            On 07/24/2017 23:43, Luper Rouch wrote:Hi, how was the package compiled?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flupke/pypotrace","title":"flupke/pypotrace","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flupke/pypotrace"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flupke in #13: Hi, how was the package compiled?"}],"action":{"name":"View Issue","url":"https://github.com/flupke/pypotrace/issues/13#issuecomment-317464287"}}}

**Comment by flupke** [comment]
Yes, you should try to do a clean recompile of pypotrace

**Comment by ClinuxMDL** [comment]
I am a fresh for compile something. So, How could I recompile pypotrace ? Any post or blog? 
            On 07/25/2017 00:20, Luper Rouch wrote:Yes, you should try to do a clean recompile of pypotrace

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flupke/pypotrace","title":"flupke/pypotrace","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flupke/pypotrace"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flupke in #13: Yes, you should try to do a clean recompile of pypotrace"}],"action":{"name":"View Issue","url":"https://github.com/flupke/pypotrace/issues/13#issuecomment-317475456"}}}
