### ISSUE TITLE
import error in OS X

### ISSUE THREAD

**Issue by wongongv** [flupke/pypotrace#17]
Hi!
I have a problem importing potrace in python3.6 (tried in 2.7 and got the same error)

I tested it on High Sierra and El Capitan.

Error message is as follow

>>> import potrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wonjunson/Downloads/svg/lib/python3.6/site-packages/pypotrace/potrace/__init__.py", line 1, in <module>
    from potrace._potrace import *
ModuleNotFoundError: No module named 'potrace._potrace'

there was no module _potrace.py in the folder. There were _potrace.pyx and _potrace.pyd

Could you help me deal with this problem?
Thank you!

**Comment by flupke** [comment]
Hi, looks like the Cython module was not compiled, try 
```
$ python setup.py build_ext --inplace
```

**Comment by h4k1m0u** [comment]
I had the same problem with Python 3.6.9, and it worked using what was suggested by @flupke.
I wonder if with newer versions of Python, pypotrace works with pip without having to install it on the local folder.
