### ISSUE TITLE
ImportError: libagg.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ousinkou** [flupke/pypotrace#38]
I meet this problem when I run the example. I check the libagg library in my system but only libagg.a exists. 
The method I install libagg-dev is same as what's described in README. 
I doubt  libagg-dev become static library instead of dynamic library in ubuntu18.04.  Any one help?

**Comment by flupke** [comment]
The .so library should be in the non `-dev` package.

**Comment by ousinkou** [comment]
@flupke  But apt-get can't find libagg, only libagg-dev

**Comment by flupke** [comment]
Looks like it's named `libagg2`: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libagg&searchon=names

**Comment by ousinkou** [comment]
@flupke Thanks, but ubuntu18.04 can't find libagg2, that link says it's only supported by Ubuntu20.04.

**Comment by flupke** [comment]
Sorry then I don't know
