### ISSUE TITLE
Installing Pypotrace

### ISSUE THREAD

**Issue by WombatBob** [flupke/pypotrace#8]
"I extracted both packages in my C:\src folder. Both are easy to build by executing ./configure; make and ./autogen.sh; make respectively, on MSYS prompt."
Just typing "./configure" and/or ".autogen.sh," even in the right directory, didn't work; apparently those commands aren't recognised.

"First, includes paths:" What does this mean? How do I "include paths" and where??? Is this still in Msys?

"libdirs for libraries we build above." What does this mean? is this still in Msys?
"We can make pypotrace build command, and execute it." Using Msys?
"Finally install the package." Using Msys?

**Comment by WombatBob** [comment]
How do I use "setup.py"???

**Comment by flupke** [comment]
Sorry I can't help you as I don't have access to a Windows box.
